apiVersion: v1
kind: Service
metadata:
  name: demo-postgres
spec:
  selector:
    app: demo-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-postgres
  template:
    metadata:
      labels:
        app: demo-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "supersecret"
        - name: POSTGRES_DB
          value: "ecommerce"
        ports:
        - containerPort: 5432