apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true" 
        vault.hashicorp.com/role: "ecommerce-app-role" 
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/ecommerce-db-role" 
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/ecommerce-db-role" -}}
          export DB_USER="{{ .Data.username }}"
          export DB_PASS="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: demo-app-sa
      containers:
      - name: alpine-bash-tester
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache postgresql-client

            while true; do
              echo "-------------------------------------"
              if [ -f /vault/secrets/db-creds ]; then
                source /vault/secrets/db-creds

                echo "[$(date)] Vault dosyasindan okunan kullanici: $DB_USER"
                echo "[$(date)] Vault dosyasindan okunan sifre: $DB_PASS"

                export PGPASSWORD=$DB_PASS
                psql -h demo-postgres -U $DB_USER -d ecommerce -c "SELECT 1;" > /dev/null 2>&1

                if [ $? -eq 0 ]; then
                  echo "bağlantı sağlandı"
                else
                  echo "bağlantı sıkıntılı"
                fi
              else
                echo "Vault dosyası henüz oluşmadı, Sidecar bekleniyor..."
              fi

              sleep 3
            done