apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata:
  name: backend-db-external-secret
  namespace: demo-app
spec: 
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: db-secret 
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: secret/backend-api/database
        property: password