apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grade-submission
    repo: ../../../helm/grade-submission
    releaseName: prod-release
    version: 0.1.0
    valuesFile: values.yaml
    includeCRDs: false

patches:
  - path: initcontainer-patch.yaml
    target:
      kind: Deployment
      name: prod-release-grade-submission-api

namePrefix: prod-
