apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: vault-dynamic-secret-demo
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: "https://github.com/EyupCanbay/argocd"
    targetRevision: HEAD
    path: vault/vault-dynamic-secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault-dynamic-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
    
